name: enem
version: '1.0'
profile: enem

model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']

models:
  enem:
    staging:
      +materialized: view
      stg_resultados:
        +materialized: table
    intermediate:
      +materialized: view

seeds:
  enem:
    co_prova:
      +column_types:
        co_prova: integer
        is_regular: boolean